### GET BOOKS
GET http://localhost:4004/odata/v4/book-rater/Books

### GET BOOKS expand authors
GET http://localhost:4004/odata/v4/book-rater/Books?$expand=authors

### GET BOOKS expand authors name
GET http://localhost:4004/odata/v4/book-rater/Books?$select=ID,title,descr,averageRating&$expand=authors($expand=author($select=name))

### GET specific book
GET http://localhost:4004/odata/v4/book-rater/Books(4c3b2a1f-9e8d-7c6b-5a4f-3e2d1c0b9a8f)?$expand=Ratings,authors($expand=author($select=name))

### Add Rating to Existing Book (via Navigation)
# @name Books_AddRating
POST http://localhost:4004/odata/v4/book-rater/Books/4c3b2a1f-9e8d-7c6b-5a4f-3e2d1c0b9a8f/Ratings
Content-Type: application/json


{
  "pos": 1,
  "rating": 5,
  "comment": "Excellent book on lean methodologies!"
}

### POST Book with author reference
POST http://localhost:4004/odata/v4/book-rater/Books
Content-Type: application/json

{
  "title": "The Infinite Game",
  "authors": [
    {
      "author": {
        "ID": "d1a3f8b4-6c2e-4a9f-b2e7-2a3c4d5e6f70"
      }
    }
  ],
  "Ratings": [
    {
      "pos": 1,
      "rating": 4,
      "comment": "Good blend of concepts and practice"
    }
  ]
}

### GET AUTHORS
GET http://localhost:4004/odata/v4/book-rater/Authors(d1a3f8b4-6c2e-4a9f-b2e7-2a3c4d5e6f70)?$expand=booksBy($expand=up_)

### DELETE a book
DELETE http://localhost:4004/odata/v4/book-rater/Books(2f3e4d5c-6b7a-8c9d-0e1f-2a3b4c5d6e7f)

### DELETE an author
DELETE http://localhost:4004/odata/v4/book-rater/Authors(9f7b2c6e-3e4b-4e7a-9a1b-1f2d3c4b5a6d)

### Create an Author
POST http://localhost:4004/odata/v4/book-rater/Authors
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "country_code": "GB",
  "dateOfBirth": "1815-12-10"
}

### Associate exsting book to existing author
POST http://localhost:4004/odata/v4/book-rater/Books(2f3e4d5c-6b7a-8c9d-0e1f-2a3b4c5d6e7f)/authors
Content-Type: application/json

{
  "author_ID": "d1a3f8b4-6c2e-4a9f-b2e7-2a3c4d5e6f70"
}

### POST Book Rating
POST http://localhost:4004/odata/v4/book-rater/Books.Ratings


## Tests before refactoring the rating entity
# ### POST book rating (WHEN IT WAS UNBOUND)
# POST  http://localhost:4004/odata/v4/book-rater/Books.rateBook()
# Content-Type: application/json

# {
#   "bookId": "4c3b2a1f9e8d7c6b5a4f3e2d1c0b9a8f",
#   "rating": 5,
#   "comment": "good"
# }

# ### POST bound book rating
# POST http://localhost:4004/odata/v4/book-rater/Books(4c3b2a1f-9e8d-7c6b-5a4f-3e2d1c0b9a8f)/rateBook
# Content-Type: application/json

# {
#   "rating": 5,
#   "comment": "good"
# }
